# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb7d684bd274859dc3e4c2ff67d6ebc936f26368b996ce023ca9bff86f0e6a101b3a653983a05a8921b789bb89289765bf6e57d22bda2a2a819d218db3b9c989

test:
  secret_key_base: 0e63ee4ee006c28dfa240c521fa88882b3d48941309970c6b7e273b51290ffb31f957ffe8c664d52dc079182c3deb043f624f8d511bc529844e7131bcb8c5e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
