source 'https://rubygems.org'

gem "acts-as-taggable-on", "~> 3.5"
gem "bluecloth", "~> 2.2"
gem "formtastic", "~> 3.1"
gem "geokit", "~> 1.9.0"
gem "htmlentities", "~> 4.3"
gem "jquery-ui-rails", "~> 5.0"
gem "loofah", "~> 2.0"
gem "loofah-activerecord", "~> 1.2"
gem "lucene_query", "0.1"
gem "nokogiri"
gem "paper_trail_manager", "~> 0.5.0"
gem "rack-contrib", "~> 1.0"
gem "rails-observers"
gem "rails_autolink", "~> 1.1"
gem "rest-client", "~> 1.8"
gem "ri_cal", "~> 0.8.8"
gem "sass", "~> 3.2"
gem "sass-rails"
gem "sunspot_rails", "~> 2.1"
gem "utf8-cleaner", "~> 0.0.6"
gem "validate_url", "~> 1.0"
gem "will_paginate", "~> 3.0"

gem "appraisal", "~> 2.0"
gem "capybara", "~> 2.4"
gem "coveralls", "~> 0.8.1"
gem "database_cleaner", "~> 1.4"
gem "factory_girl_rails", "~> 4.5"
gem "faker", "~> 1.4"
gem "gem-release", "~> 0.7"
gem "poltergeist", "~> 1.6"
gem "rspec-activemodel-mocks", "~> 1.0.2"
gem "rspec-collection_matchers", "~> 1.1"
gem "rspec-its", "~> 1.1"
gem "rspec-rails", "~> 3.2"
gem "simplecov", "~> 0.10.0"
gem "sqlite3", "~> 1.3"
gem "sunspot_solr", "~> 2.1"
gem "timecop", "~> 0.7.1"
gem "webmock", "~> 1.20"

gem 'devise'
gem 'jquery-turbolinks'
gem 'bootstrap-sass'
gem 'momentjs-rails', '>= 2.9.0'
gem 'bootstrap3-datetimepicker-rails', '~> 4.14.30'
gem 'omniauth-weibo-oauth2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.5'


# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

