# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1739e96312daffa39d1606895da032e06017cae95d1991ceaa0bd399c0317da6e167e353fb3b25f5e7792768cc280d64b3dd0de546d256ef72eab785b9dd03

test:
  secret_key_base: 9f0a1f1a9389df78f1df77360b2aeecb687164548e39af850155db9604c433e5332edb70c140783e09b7d200de7a973f002fe2402f30c8a8205ca7abec0c5bbe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
